name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # Se activa al hacer push a main
  pull_request:
    branches: [ "main" ] # Se activa al intentar fusionar una rama

jobs:
  build:
    runs-on: ubuntu-latest # Sistema Operativo del servidor

    steps:
      - uses: actions/checkout@v3 # 1. GitHub clona tu repo

      - name: Set up JDK 17
        uses: actions/setup-java@v3 # 2. Instala Java 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run JUnit tests
        run: mvn -.batch-mode test # 3. Lanza los tests